import 'package:test/test.dart';
import 'package:adventofcode_2023/day11.dart';

void main() {
  test('day11 ...', () async {
    var testData1 = '''
...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....
''';

    expect(Day11().solve(Day11.parseData(testData1), 2), equals(374));
    expect(Day11().solve(Day11.parseData(testData1), 10), equals(1030));
    expect(Day11().solve(Day11.parseData(testData1), 100), equals(8410));
  });
}
